{
 "title": "Streaming service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Quote updates per minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(quote_updates_total[1m])"
    }
   ]
  },
  {
   "title": "WebSocket connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "connections_count" }
   ]
  },
  {
   "title": "Quote service response time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "quote_load_seconds{quantile=\"0.98\", exception=\"none\"}"
    }
   ]
  }
 ]
}